import {
  Monitor, Users, Building2, Layers, Landmark,
  BedSingle, DoorOpen, Star,
  Wifi, Coffee, ShieldCheck, CarFront, Printer, Presentation,
} from 'lucide-react';

export const coworkingSpaces = [
  {
    id: 'solo',
    title: 'โต๊ะเดี่ยว Solo Desk',
    desc: 'พื้นที่ส่วนตัวพร้อมปลั๊กไฟ Wi-Fi ความเร็วสูง เหมาะสำหรับฟรีแลนซ์และนักพัฒนา',
    image: '/images/solo.png',
    icon: Monitor,
    badge: 'ยอดนิยม',
    badgeType: 'popular',
    features: ['Wi-Fi 1Gbps', 'ปลั๊กไฟ', 'ล็อคเกอร์', 'กาแฟฟรี'],
    priceDaily: 350,
    priceMonthly: 5900,
    capacity: '1 คน',
  },
  {
    id: 'group',
    title: 'โซนกลุ่ม Group Zone',
    desc: 'พื้นที่สำหรับทำงานเป็นทีม 4-8 คน โต๊ะใหญ่ จอ TV สำหรับประชุม',
    image: '/images/group.png',
    icon: Users,
    badge: null,
    badgeType: '',
    features: ['โต๊ะรวม', 'จอ TV', 'ไวท์บอร์ด', 'Wi-Fi', 'เครื่องดื่ม'],
    priceDaily: 1200,
    priceMonthly: 18000,
    capacity: '4-8 คน',
  },
  {
    id: 'office',
    title: 'ห้องออฟฟิศ Private Office',
    desc: 'ห้องส่วนตัวพร้อมเฟอร์นิเจอร์ครบชุด เหมาะสำหรับทีมขนาดเล็ก',
    image: '/images/office.png',
    icon: Building2,
    badge: 'แนะนำ',
    badgeType: '',
    features: ['ห้องส่วนตัว', 'เฟอร์นิเจอร์ครบ', 'ห้องประชุม', 'ที่จอดรถ', 'Wi-Fi'],
    priceDaily: 3500,
    priceMonthly: 45000,
    capacity: '5-15 คน',
  },
  {
    id: 'floor',
    title: 'เช่าทั้งชั้น Full Floor',
    desc: 'พื้นที่ทั้งชั้น ออกแบบได้ตามต้องการ พร้อมระบบรักษาความปลอดภัย',
    image: '/images/floor.png',
    icon: Layers,
    badge: 'Premium',
    badgeType: 'premium',
    features: ['พื้นที่ทั้งชั้น', 'ออกแบบเอง', 'รปภ.', 'ที่จอดรถ 10 คัน', 'ห้องประชุม'],
    priceDaily: 15000,
    priceMonthly: 180000,
    capacity: '30-80 คน',
  },
  {
    id: 'building',
    title: 'เช่าทั้งตึก Entire Building',
    desc: 'เหมาะสำหรับเปิดบริษัท พร้อมจดทะเบียนบริษัท ออฟฟิศครบวงจร',
    image: '/images/building.png',
    icon: Landmark,
    badge: 'Enterprise',
    badgeType: 'premium',
    features: ['ทั้งตึก', 'จดทะเบียนบริษัท', 'รปภ. 24 ชม.', 'ที่จอดรถ 30+', 'ลิฟต์'],
    priceDaily: 45000,
    priceMonthly: 500000,
    capacity: '100+ คน',
  },
];

export const stayRooms = [
  {
    id: 'capsule',
    title: 'แคปซูลนอน Capsule Pod',
    desc: 'พื้นที่นอนส่วนตัวแบบแคปซูล พร้อมผ้าม่าน แอร์ ปลั๊กไฟ USB',
    image: '/images/capsule.png',
    icon: BedSingle,
    badge: 'ประหยัด',
    badgeType: 'popular',
    features: ['แอร์', 'ปลั๊ก USB', 'ล็อคเกอร์', 'ผ้าเช็ดตัว'],
    priceNightly: 450,
    priceMonthly: 8500,
    capacity: '1 คน',
  },
  {
    id: 'single-room',
    title: 'ห้องเดี่ยว Single Room',
    desc: 'ห้องส่วนตัวพร้อมเตียง โต๊ะทำงาน ห้องน้ำในตัว เหมาะสำหรับพักผ่อน',
    image: '/images/single-room.png',
    icon: DoorOpen,
    badge: null,
    badgeType: '',
    features: ['ห้องน้ำในตัว', 'Wi-Fi', 'แอร์', 'ตู้เย็นเล็ก', 'TV'],
    priceNightly: 890,
    priceMonthly: 15000,
    capacity: '1-2 คน',
  },
  {
    id: 'suite',
    title: 'ห้องสวีท Suite Room',
    desc: 'ห้องพักหรูพร้อมห้องนั่งเล่น ครัวเล็ก เหมาะสำหรับพักระยะยาว',
    image: '/images/suite.png',
    icon: Star,
    badge: 'Premium',
    badgeType: 'premium',
    features: ['ห้องนั่งเล่น', 'ครัวเล็ก', 'ห้องน้ำใหญ่', 'เครื่องซักผ้า', 'ระเบียง'],
    priceNightly: 1800,
    priceMonthly: 28000,
    capacity: '1-3 คน',
  },
];

export const featuresList = [
  { Icon: Wifi, title: 'Wi-Fi ความเร็วสูง', desc: 'อินเทอร์เน็ตไฟเบอร์ 1Gbps เสถียรตลอด 24 ชม.' },
  { Icon: Coffee, title: 'เครื่องดื่มฟรี', desc: 'กาแฟ ชา น้ำ พร้อมเสิร์ฟตลอดวัน' },
  { Icon: ShieldCheck, title: 'ปลอดภัย 24 ชม.', desc: 'ระบบ CCTV กุญแจอิเล็กทรอนิกส์ รปภ. ตลอด' },
  { Icon: CarFront, title: 'ที่จอดรถ', desc: 'ที่จอดรถฟรีสำหรับสมาชิกรายเดือน' },
  { Icon: Printer, title: 'เครื่องพิมพ์', desc: 'บริการพิมพ์เอกสาร สแกน ถ่ายเอกสาร' },
  { Icon: Presentation, title: 'ห้องประชุม', desc: 'ห้องประชุมพร้อมอุปกรณ์ จองง่ายผ่านแอป' },
];
